# -*- coding: utf-8 -*-

# タイトル付与
set-option -g set-titles on

# ペイン開始番号
set-option -g base-index 1

# -r による連続入力の待機時間(ミリ秒)
set-option -g repeat-time 1000

# 256色表示
set-option -g default-terminal "xterm-256color"

# コピーモード操作 emacs
set-option -g mode-keys emacs

# ヒストリ上限 (5,000行)
set-option -g history-limit 5000

# 文字コード
# set-window-option -g status-utf8 on

# prefix + r で設定ファイル再読み込み
bind-key -N "設定再読み込み" r source-file ~/.tmux.conf \; display-message "Config reloaded."

# ----------------------------------------------------------

# ペイン同時入力切り替え
set-option -g synchronize-panes off
bind-key -N "Pane同期入力オン" e setw synchronize-panes on \;  display "Synchronize-panes: On"
bind-key -N "Pane同期入力オフ" E setw synchronize-panes off \; display "Synchronize-panes: Off"

# マウス操作切り替え
set-option -g mouse on
bind-key -N "Mouse操作オン" m set-option -g mouse on \;  display "Mouse: On"
bind-key -N "Mouse操作オフ" M set-option -g mouse off \; display "Mouse: Off"

bind-key -n WheelUpPane   select-pane -t= \; copy-mode -e \; send-keys -M
bind-key -n WheelDownPane select-pane -t= \;                 send-keys -M

# ----------------------------------------------------------

# ステータスライン更新間隔 (default: 8)
set-option -g status-interval 8

set-option -g status-fg colour234
set-option -g status-bg colour60
set-option -g status-left-style bg=colour147,fg=colour234,none
set-option -g status-right-style bg=colour147,fg=colour234,none

set-option -g status-left "\
#[fg=colour234,bg=colour147]#{?client_prefix,#[fg=colour147]#[bg=colour234],} #S:#I.#P #h #(get_ime) \
#[fg=colour147,bg=colour234]#{?client_prefix,#[fg=colour234]#[bg=colour60],#[fg=colour147]#[bg=colour60]}\uE0C6\
#[fg=colour234,bg=colour60]#{?client_prefix,#[fg=colour234]#[bg=colour60],#[fg=colour234]#[bg=colour60]}  "
set-option -g status-left-length 30
set-option -g status-right "\
#[fg=colour147,bg=colour60]\uE0C7\
#[fg=colour234,bg=colour147] #(batt_status) #(batt_percentage) \
#[fg=colour147,bg=colour60]\uE0C6 #(get_volume)\
#[fg=colour147,bg=colour60] \uE0C7\
#[fg=colour234,bg=colour147] %Y/%m/%d(%a) %H:%M "
set-option -g status-right-length 120

set-option -g window-status-current-style bg=colour227,fg=blue,none
set-option -g window-status-style bg=colour60,fg=default,none


# ----------------------------------------------------------

# 区切り線のスタイル
set-option -g pane-active-border-style bg=black,fg=colour75,none
set-option -g pane-border-style bg=black,fg=colour237,none
set-option -g pane-border-status bottom
set-option -g pane-border-format " [###P: #T (#{pane_current_command})] "

# ----------------------------------------------------------

# キーバインド変更
unbind-key %
unbind-key '"'
bind-key - split-window -v
bind-key | split-window -h

# Pre + i でPane番号を大きく表示
bind-key i display-panes

# Ctrl押しっぱなしでも動作するように変更
bind-key -N "新しいWindowを作る" C-c new-window
bind-key -N "Sessionをデタッチ" C-d detach
bind-key -N "次のWindowへ移動" C-n next-window
bind-key -N "前のWindowへ移動" C-p previous-window

# Ctrl + h/j/k/l でペイン移動
bind-key -N "左のPaneに移動" -r M-h select-pane -L
bind-key -N "下のPaneに移動" -r M-j select-pane -D
bind-key -N "上のPaneに移動" -r M-k select-pane -U
bind-key -N "右のPaneに移動" -r M-l select-pane -R

# Pre + q で現在のSessionをkill-sessionする
bind-key -N "現在のSessionをKill (確認あり)" q confirm-before "kill-session"

# Pre + C-q でtmuxを終了(kill-server)する
bind-key -N "tmuxを終了する (確認あり)" C-q confirm-before "kill-server"

# session,window,pane のツリー表示 --> 選択
bind-key -n -N "session,window,paneをツリー表示" M-a choose-tree
bind-key -n -N "window,paneをツリー表示" M-w choose-tree -w
bind-key -n -N "sessionをツリー表示" M-e choose-session
