# -*- coding: utf-8 -*-

# タイトル付与
set -g set-titles on

# ペイン開始番号
set -g base-index 1

# -r による連続入力の待機時間(ミリ秒)
set -g repeat-time 1000

# 256色表示
set -g default-terminal "xterm-256color"

# コピーモード操作 emacs
setw -g mode-keys emacs

# ヒストリ上限 (5,000行)
set -g history-limit 5000

# 文字コード
# set-window-option -g status-utf8 on

# prefix + r で設定ファイル再読み込み
bind -N "設定再読み込み" r source-file ~/.tmux.conf \; display-message "Config reloaded."

# ----------------------------------------------------------

# ペイン同時入力切り替え
set -g synchronize-panes off
bind -N "Pane同期入力オン" e setw synchronize-panes on \;  display "Synchronize-panes: On"
bind -N "Pane同期入力オフ" E setw synchronize-panes off \; display "Synchronize-panes: Off"

# マウス操作切り替え
set -g mouse on
bind -N "Mouse操作オン" m set -g mouse on \;  display "Mouse: On"
bind -N "Mouse操作オフ" M set -g mouse off \; display "Mouse: Off"

bind -n WheelUpPane   select-pane -t= \; copy-mode -e \; send-keys -M
bind -n WheelDownPane select-pane -t= \;                 send-keys -M

# ----------------------------------------------------------

# ステータスライン更新間隔 (default: 15)
set -g status-interval 8

set -g status-fg colour234
set -g status-bg colour60
set -g status-left-style bg=colour147,fg=colour234,none
set -g status-right-style bg=colour147,fg=colour234,none

set -g status-left "\
#[fg=colour234,bg=colour147]#{?client_prefix,#[fg=colour147]#[bg=colour234],} #S:#I.#P #h #(get_ime) \
#[fg=colour147,bg=colour234]#{?client_prefix,#[fg=colour234]#[bg=colour60],#[fg=colour147]#[bg=colour60]}\uE0C6\
#[fg=colour234,bg=colour60]#{?client_prefix,#[fg=colour234]#[bg=colour60],#[fg=colour234]#[bg=colour60]}  "
set -g status-left-length 30
set -g status-right "\
#[fg=colour147,bg=colour60]\uE0C7\
#[fg=colour234,bg=colour147] #(batt_status) #(batt_percentage) \
#[fg=colour147,bg=colour60]\uE0C6 #(get_volume)\
#[fg=colour147,bg=colour60] \uE0C7\
#[fg=colour234,bg=colour147] %Y/%m/%d(%a) %H:%M "
set -g status-right-length 120

setw -g window-status-current-style bg=colour227,fg=blue,none
setw -g window-status-style bg=colour60,fg=default,none


# ----------------------------------------------------------

# 区切り線のスタイル
set -g pane-active-border-style bg=black,fg=colour75,none
set -g pane-border-style bg=black,fg=colour237,none
set -g pane-border-status bottom
set -g pane-border-format " [###P: #T (#{pane_current_command})] "

# ----------------------------------------------------------

# キーバインド変更
unbind %
unbind '"'
bind - split-window -v
bind | split-window -h

# Pre + i でペイン番号を大きく表示
bind i display-panes

# Ctrl押しっぱなしでも動作するように変更
bind C-c new-window
bind C-d detach
bind C-n next-window
bind C-p previous-window

# Ctrl + h/j/k/l でペイン移動
bind -N "左のペインに移動" -r M-h select-pane -L
bind -N "下のペインに移動" -r M-j select-pane -D
bind -N "上のペインに移動" -r M-k select-pane -U
bind -N "右のペインに移動" -r M-l select-pane -R

# Pre + q で現在のセッションをkill-sessionする
bind -N "現在のSessionをKill (確認あり)" q confirm-before 'kill-session'

# Pre + C-q でtmuxを終了(kill-server)する
bind -N "tmuxを終了する (確認あり)" C-q confirm-before 'kill-server'

