#!/usr/bin/env bash
#
# - 󰚥 : \Uf06a5
# - 󰁹 : \Uf0079
# - 󰂂 : \Uf0081
# - 󰂄 : \Uf0084
# - 󰂑 : \Uf0091
# - 󱈑 : \Uf1211

status_plugged='󰚥'
status_batt_finishing_charge='󰁹'
status_batt_charging='󰂄'
status_batt_dischargeing='󰂂'
status_batt_attached='󱈑'
status_batt_unknown='󰂑'

print_icon_status () {
  _stat=$(pmset -g batt)
  power_supply=$(cat <<< "$_stat" | head -1 | sed -e "s/Now drawing from '\(.*\)'/\1/g")
  batt_status=$(cat <<< "$_stat" | awk -F'; *' 'NR==2{ print $2 }')

  if [[ $power_supply =~ (AC Power) ]]; then
    _plug="$status_plugged "
  fi

  if [[ $batt_status =~ (finishing charge) || $batt_status =~ (charged) ]]; then
    printf "%s%s" "$_plug" "$status_batt_finishing_charge"
  elif [[ $batt_status =~ (^charging) ]]; then
    printf "%s%s" "$_plug" "$status_batt_charging"
  elif [[ $batt_status =~ (^discharging) ]]; then
    printf "%s%s" "$_plug" "$status_batt_dischargeing"
  elif [[ $batt_status =~ (attached) ]]; then
    printf "%s%s" "$_plug" "$status_batt_attached"
  else
    printf "%s" $status_batt_unknown
  fi
}

main () {
  print_icon_status
}

main
