#!/bin/zsh
# shellcheck disable=SC1071

SOUND_INFO=$(osascript -e "get volume settings")
if [ -n "${SOUND_INFO}" ]; then
  volume_level=$(echo "${SOUND_INFO}" | awk -F', ' '{ print $1 }')
  mute_flag=$(echo "${SOUND_INFO}" | awk -F', ' '{ print $4 }')

  if [ "${mute_flag}" = "output muted:true" ]; then
    volume="   🔇   "
  else
    sound_volume=$(expr $(echo $SOUND_INFO | awk -F', ' '{ print $1 }' | grep -o '[0-9]\{1,3\}') / 13 + 1)
    str=""
    for (( i=1; i < 9; i++ )); do
      if [ $i -le $sound_volume ]; then
        str="${str}\u258${i}"
      else
        str="${str} "
      fi
    done
    volume="${str}"
  fi
  echo "volume: #[bold]${volume}#[default]"
fi
