#!/bin/zsh

readonly red='0;31'
readonly green='0;32'
readonly brown='0;33'
readonly blue='0;34'
readonly gray='0;37'
readonly org='0;0'

# EXCLUDES="and not sqlite"

clr_echo ()
{
  msg=${1}
  color=${2:-$(echo $org)}
  echo -e "\033[${color}m${msg}\033[${org}m"
}

# main

clr_echo 'Update start...' $brown
sudo port selfupdate

clr_echo 'Check outdated items...' $brown
outdated_items=$(sudo port outdated 2> /dev/null)
if [ $#outdated -ne 0 ]; then
  clr_echo 'Upgrade available:' $green
  echo $outdated_items
  sudo port upgrade outdated ${EXCLUDES}

  clr_echo 'Uninstall outdated items:' $green
  port installed | grep -Ev "(active|installed)" | perl -npe '`sudo port uninstall$_`;'
else
  clr_echo ' No outdated items.' $green
fi

clr_echo 'Update complete.' $brown

clr_echo 'Check non-requested items...' $brown
non_dependents=$(port installed | grep -v 'following' | awk '{print $1}' | xargs port dependents | grep 'has not dependents' | awk '{print $1}')
requested=$(port installed requested | grep -v 'following' | awk '{print $1}')
unexpected_non_requested=$(diff <(echo $requested) <(echo $non_dependents) | grep -E '^\+[^+]+')

if [ $#unexpected_non_requested -ne 0 ]; then
  clr_echo 'Non-requested items:' $green
  echo $unexpected_non_requested | tr -d "+"
else
  clr_echo ' All items have been requested or have been dependent.' $green
fi

date
# END
