# -*- coding: utf-8 -*-
# キーバインド

unbind-key %
unbind-key '"'
bind-key - split-window -v
bind-key | split-window -h

# Pre + i でPane番号を大きく表示
bind-key i display-panes

# Ctrl押しっぱなしでも動作するように変更
bind-key -N "新しいWindowを作る" C-c new-window
bind-key -N "Sessionをデタッチ" C-d detach
bind-key -N "次のWindowへ移動" C-n next-window
bind-key -N "前のWindowへ移動" C-p previous-window

# Ctrl + h/j/k/l でペイン移動
bind-key -N "左のPaneに移動" -r M-h select-pane -L
bind-key -N "下のPaneに移動" -r M-j select-pane -D
bind-key -N "上のPaneに移動" -r M-k select-pane -U
bind-key -N "右のPaneに移動" -r M-l select-pane -R

# Pre + q で現在のSessionをkill-sessionする
bind-key -N "現在のSessionをKill (確認あり)" q confirm-before "kill-session"

# Pre + C-q でtmuxを終了(kill-server)する
bind-key -N "tmuxを終了する (確認あり)" C-q confirm-before "kill-server"

# session,window,pane のツリー表示 --> 選択
bind-key -n -N "session,window,paneをツリー表示" M-a choose-tree
bind-key -n -N "window,paneをツリー表示" M-w choose-tree -w
bind-key -n -N "sessionをツリー表示" M-e choose-session

# prefix + r で設定ファイル再読み込み
bind-key -N "設定再読み込み" r source-file ~/.tmux.conf \; display-message "Config reloaded."

# ----------------------------------------------------------

# ペイン同時入力切り替え
set-option -g synchronize-panes off
bind-key -N "Pane同期入力オン" e setw synchronize-panes on \;  display "Synchronize-panes: On"
bind-key -N "Pane同期入力オフ" E setw synchronize-panes off \; display "Synchronize-panes: Off"

# マウス操作切り替え
set-option -g mouse on
bind-key -N "Mouse操作オン" m set-option -g mouse on \;  display "Mouse: On"
bind-key -N "Mouse操作オフ" M set-option -g mouse off \; display "Mouse: Off"

bind-key -n WheelUpPane   select-pane -t= \; copy-mode -e \; send-keys -M
bind-key -n WheelDownPane select-pane -t= \;                 send-keys -M
