# -*- coding: utf-8 -*-
# ステータスライン (要 NerdFonts)
#
# separators:
# -  : \ue0b0      nf-pl-left_hard_divider
# -  : \ue0b1      nf-pl-left_soft_divider
# -  : \ue0b2      nf-pl-right_hard_divider
# -  : \ue0b3      nf-pl-right_soft_divider
# -  : \ue0bc      nf-ple-upper_left_triangle
# -  : \ue0be      nf-ple-upper_right_triangle
# -  : \ue0c4      nf-ple-pixelated_squares_small
# -  : \ue0c5      nf-ple-pixelated_squares_small_mirrored
# -  : \ue0c6      nf-ple-pixelated_squares_big
# -  : \ue0c7      nf-ple-pixelated_squares_big_mirrored
# -  : \ue0d2      nf-ple-trapezoid_top_bottom
# -  : \ue0d4      nf-ple-trapezoid_top_bottom_mirrored
# -  : \ue0d6      nf-ple-right_hard_divider_inverse
# -  : \ue0d7      nf-ple-left_hard_divider_inverse
# - 󰇙 : \U000f01d9  nf-md-dots_vertical
#
# icons:
# -  : \uf017      nf-fa-clock
# -  : \uf073      nf-fa-calendar

# set-option -g window-status-current-style bg=colour227,fg=blue,none
# set-option -g window-status-style bg=colour60,fg=default,none

# ステータスライン更新間隔 (default: 1)
set-option -g status-interval 1

# ステータスライン全体の foreground と background
set-option -g status-bg "#3f3f3f"
set-option -g status-fg "#dfdf00"

# ステータスライン: left, right 個別の foreground と background
set-option -g status-left-style "bg=#3f3f3f,fg=#dfdf00"
set-option -g status-right-style "bg=#3f3f3f,fg=#dfdf00"

# ステータスライン: left のコンテンツ
set-option -g status-left-length 30
set-option -g status-left "\
#{?pane_in_mode,#[bg=#00afff bold#,fg=#3f3f3f] *COPY* ,#[bold] INSERT }#[default]\
#[bg=#3f3f3f,fg=#dfdf00]#{?client_prefix,#[reverse],} #S:#I.#P #h #(get_ime)#[default]  "

# ステータスライン: right のコンテンツ
set-option -g status-right-length 120
set-option -g status-right "   #(get_wifi_info)   #(batt_status) #(batt_percentage)   #(get_volume)   \uf017 %H:%M   \uf073 %Y/%m/%d(%a)"

# ウィンドウステータスのコンテンツ
set-option -g window-status-format " #I:#W#{?window_flags,#{window_flags}, }"
set-option -g window-status-current-format "#[fg=#3f3f3f,bg=#dfdf00] #I:#W#{?window_flags,#{window_flags}, }"
set-option -g window-status-separator "#[fg=#808080,bg=#3f3f3f]\U000f01d9#[default]"
