# -*- coding: utf-8 -*-

# タイトル付与
set-option -g set-titles on

# ペイン開始番号
set-option -g base-index 1

# -r による連続入力の待機時間(ミリ秒)
set-option -g repeat-time 1000

# 256色表示
set-option -g default-terminal "xterm-256color"

# コピーモード操作 emacs
set-option -g mode-keys emacs

# ヒストリ上限 (5,000行)
set-option -g history-limit 5000

# 文字コード
# set-window-option -g status-utf8 on

# ----------------------------------------------------------

# 区切り線のスタイル
set-option -g pane-active-border-style bg=black,fg=colour75,none
set-option -g pane-border-style bg=black,fg=colour237,none
set-option -g pane-border-status bottom
set-option -g pane-border-format " [###P: #T (#{pane_current_command})] "

# ----------------------------------------------------------

# キーバインドとステータスラインの設定を読み込む
source-file ~/.config/tmux/keybinding.conf
source-file ~/.config/tmux/status.conf
