# Commands
# brew "bat"
# brew "duckdb"
# brew "fzf"
# brew "gh"
# brew "ghq"
# brew "git"
# brew "herdr"
# brew "jj"
# brew "jq"
# brew "just"
# brew "mysql-client"
# brew "peco"
# brew "pinact"
# brew "pkgconf"
# brew "ripgrep"
# brew "tmux"
# brew "yq"
# brew "zizmor"
# brew "zoxide"

# Linters
# brew "checkmake"
# brew "shellcheck"

# Shell extensions
# brew "sheldon"
# brew "starship"

# Cask: CLI Applications
cask "gcloud-cli"
# cask "claude-code"

# Cask: GUI Applications
cask "docker-desktop"
# cask "visual-studio-code"
# cask "zed"

# Cask: Fonts
# cask "font-cica"
# cask "font-noto-nerd-font"

# Optional: Obsoleted tools
# brew "nodenv"
# brew "pyenv"
# tap "mutagen-io/mutagen", trusted: true
# brew "mutagen-io/mutagen/mutagen", trusted: true
# brew "mutagen-io/mutagen/mutagen-compose", trusted: true
